// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import createModule from '@transcribe/shout';
import { FileTranscriber } from '@transcribe/transcriber';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'angular';
  result = '';
  transcriber: FileTranscriber;

  constructor() {
    this.transcriber = new FileTranscriber({
      createModule,
      model: '/ggml-tiny-q5_1.bin',
      workerPath: '/',
    });

    this.transcriber.init();
  }

  async transcribe() {
    if (!this.transcriber?.isReady) return;

    this.result = 'Transcribing...';

    // transcribe the file
    // there must be at least one user interaction (e.g click) before you can call this function
    const result = await this.transcriber.transcribe('/jfk.wav', {
      lang: 'en',
    });

    // do something with the result
    this.result = result.transcription.map((t) => t.text).join(' ');
  }
}

<main>
  <h1>Transcribe.js Angular Example</h1>

  <p>
    Click the button to transcribe the example wav file. (check console for
    detailed output)
  </p>

  @if(transcriber.isReady) {
  <button (click)="transcribe()">Transcribe</button>
  } @if(result) {
  <p><b>Result: </b>{{ result }}</p>
  }
</main>

<router-outlet />

// svelte/src/App.svelte
<script lang="ts">
  import createModule from "@transcribe/shout";
  import { FileTranscriber } from "@transcribe/transcriber";
  import { onMount } from "svelte";

  let transcriber: FileTranscriber;

  $: isReady = false;
  $: text = "";

  async function transcribe() {
    if (!transcriber?.isReady) return;

    text = "Transcribing...";

    // transcribe the file
    // there must be at least one user interaction (e.g click) before you can call this function
    const result = await transcriber.transcribe("/jfk.wav", { lang: "en" });

    // do something with the result
    text = result.transcription.map((t) => t.text).join(" ");
  }

  onMount(async () => {
    // create new instance
    transcriber = new FileTranscriber({
      createModule,
      model: "/ggml-tiny-q5_1.bin",
      workerPath: "/",
    });

    // and initialize the transcriber
    await transcriber.init();

    isReady = true;
  });
</script>

<main>
  <h1>Transcribe.js Svelte Example</h1>
  <p>
    Click the button to transcribe the example wav file. (check console for
    detailed output)
  </p>

  {#if isReady}
    <button on:click={transcribe}>Transcribe</button>

    {#if text}
      <p><b>Result:</b>{text}</p>
    {/if}
  {/if}
</main>
